name: kgnn_mac
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - scipy
  - pandas
  - matplotlib
  - networkx
  - tqdm
  - jupyter
  - scikit-learn
  - pip
  - shapely
  - pip:
    - jax
    - jaxlib
    - jax_md
    - jax-metal
    - flax
    - optax
    - jaxopt
    - jraph
    - e3nn-jax
    - wandb