#!/usr/bin/env python3
"""
param_search.py — Random search over EGNN hyperparameters.

Fixed problem : interior clamp (face 9) + 3 alternating moments (suite_midmoment).
Strategy      : random search — 10 parameters, 120 samples, ~2 h budget.
Results       : written progressively to data/outputs/param_search_<ts>.csv
                (interrupt at any time — partial results are kept).

Search axes:
  Loss weights : chamfer, hinge_gap, coverage, contact
  Optimizer    : learning_rate, grad_clip
  Validity     : anchoring, connectivity  (void_length = void_collinear = connectivity/6)
  Architecture : hidden_dim, num_layers

Fixed:
  target (optimization_weights) = 0  always
  void_length = void_collinear  = connectivity / 6  (always < connectivity)

Usage:
    python param_search.py               # run full search
    python param_search.py --n 20        # limit to 20 samples
    python param_search.py --seed 99     # different random order
    python param_search.py --dry-run     # print samples, don't run
"""

import os
import sys
import csv
import random
import subprocess
import datetime
import re
import argparse

# ── Search space (discrete choices per axis) ──────────────────────────────────
# Each list spans ~ one decade in log-space so random search covers it well.

SEARCH = {
    # ── Loss weights ──────────────────────────────────────────────────────────
    'chamfer':        [1000.0, 3000.0, 7000.0, 15000.0],
    'hinge_gap':      [5.0,    20.0,   60.0,   200.0],
    'coverage':       [0.3,    1.0,    3.0],
    'contact':        [0.1,    0.5,    2.0,    5.0],
    # ── Optimizer ─────────────────────────────────────────────────────────────
    'learning_rate':  [0.001,  0.003,  0.007,  0.015],
    'grad_clip':      [2.0,    7.0,    20.0],
    # ── Validity solver ───────────────────────────────────────────────────────
    'anchoring':      [300.0,  800.0,  2000.0, 5000.0],
    'connectivity':   [1000.0, 3000.0, 6000.0, 12000.0],
    # ── Architecture ──────────────────────────────────────────────────────────
    'hidden_dim':     [32,     64,     128],
    'num_layers':     [2,      3,      4],
}

N_SAMPLES   = 120      # total random draws
SUITE       = 'problems/suite_midmoment'
TMP_ARCH    = 'data/configs/architectures/_search_tmp.yaml'
RUN_TIMEOUT = 240      # seconds per run before marking as timeout

# ── Arch YAML template ────────────────────────────────────────────────────────
# - target = 0  (always)
# - void_length = void_collinear = connectivity / 6  (always < connectivity)
# - all visualization off  (skips post-training forward pass)

ARCH_TEMPLATE = """\
# Auto-generated by param_search.py — do not edit.
tessellation:
  width: 2
  height: 2
  pattern: "unit_RDQK_D"
  total_area: 3.0

target:
  type: "circle"
  center: [0.0, 0.0]
  radius: 1.0

mapping:
  map_type: gnn_egnn
  domain_restriction: 1.0
  use_shirley_chiu: false
  strict_boundary_fit: false
  learn_global_scale: false
  map_params:
    hidden_dim: {hidden_dim}
    num_layers: {num_layers}
    seed: 2

optimization_weights:
  connectivity:    {connectivity}
  non_intersection: 0
  target:          0
  arm_symmetry:    0
  void_length:     {void_length}
  void_collinear:  {void_collinear}
  boundary_rigidity: 0
  face_area:       100.0
  anchoring:       {anchoring}

training:
  num_epochs: 500
  learning_rate: {learning_rate}
  optimizer: "adam"
  lr_schedule: "cosine"
  geometric_loss_type: "boundary_vertices"
  grad_clip: {grad_clip}

loss_weights:
  chamfer:        {chamfer}
  material_area:  0.0
  stretching:     1.0
  shearing:       10.0
  bending:        0.0
  contact:        {contact}
  regularization: 0.0001
  coverage:       {coverage}
  hinge_gap:      {hinge_gap}

visualization:
  stage0: false
  stage1: false
  stage2: false
  energy_plot: false
  animation: false
  show_plots: false
  save_outputs: false
  show_hinges: false
  show_hinge_indices: false
  show_external_forces: false
  show_kinematic_blocks: false
"""

# ── Helpers ───────────────────────────────────────────────────────────────────

def random_combo(rng):
    c = {k: rng.choice(v) for k, v in SEARCH.items()}
    # Derived constraints: void must be < connectivity
    c['void_length']    = round(c['connectivity'] / 6.0, 1)
    c['void_collinear'] = round(c['connectivity'] / 6.0, 1)
    return c


def write_arch(combo):
    os.makedirs(os.path.dirname(TMP_ARCH), exist_ok=True)
    with open(TMP_ARCH, 'w') as f:
        f.write(ARCH_TEMPLATE.format(**combo))


def parse_output(stdout):
    m = re.search(r'loss=([0-9.e+\-]+)\s+chamfer=([0-9.e+\-]+)', stdout)
    chamfer = float(m.group(2)) if m else float('nan')
    loss    = float(m.group(1)) if m else float('nan')

    n_exp = stdout.count('[EXPLODING]')

    grads = re.findall(r'‖grad‖:\s*([0-9.e+\-]+)', stdout)
    final_grad = float(grads[-1]) if grads else float('nan')

    hinges = re.findall(r'HingeGap:\s*([0-9.e+\-]+)', stdout)
    final_hinge = float(hinges[-1]) if hinges else float('nan')

    return chamfer, loss, n_exp, final_grad, final_hinge


def run_combo(combo, idx, total):
    write_arch(combo)
    cmd = [sys.executable, 'train.py',
           '--arch', 'architectures/_search_tmp',
           '--suite', SUITE]

    t0 = datetime.datetime.now()
    status = 'ok'
    try:
        r = subprocess.run(cmd, capture_output=True, text=True,
                           timeout=RUN_TIMEOUT)
        stdout = r.stdout + r.stderr
        if r.returncode != 0:
            status = 'fail'
    except subprocess.TimeoutExpired:
        stdout = ''
        status = 'timeout'

    elapsed = (datetime.datetime.now() - t0).total_seconds()
    chamfer, loss, n_exp, final_grad, final_hinge = parse_output(stdout)

    print(
        f"  [{idx:3d}/{total}]"
        f"  lr={combo['learning_rate']:.4f}"
        f"  clip={combo['grad_clip']:5.1f}"
        f"  ch={combo['chamfer']:6.0f}"
        f"  hg={combo['hinge_gap']:5.1f}"
        f"  cov={combo['coverage']:.1f}"
        f"  con={combo['contact']:.1f}"
        f"  anch={combo['anchoring']:6.0f}"
        f"  conn={combo['connectivity']:6.0f}"
        f"  h={combo['hidden_dim']:3d}"
        f"  L={combo['num_layers']}"
        f"  → chamfer={chamfer:.4e}"
        f"  expl={n_exp:2d}"
        f"  {elapsed:.0f}s  [{status}]"
    )

    return {
        # search params
        'learning_rate': combo['learning_rate'],
        'grad_clip':     combo['grad_clip'],
        'chamfer_w':     combo['chamfer'],
        'hinge_gap_w':   combo['hinge_gap'],
        'coverage_w':    combo['coverage'],
        'contact_w':     combo['contact'],
        'anchoring':     combo['anchoring'],
        'connectivity':  combo['connectivity'],
        'hidden_dim':    combo['hidden_dim'],
        'num_layers':    combo['num_layers'],
        # results
        'chamfer':       chamfer,
        'loss':          loss,
        'n_explosions':  n_exp,
        'final_grad':    round(final_grad, 2),
        'final_hinge':   round(final_hinge, 4),
        'elapsed_s':     round(elapsed, 1),
        'status':        status,
    }

# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--n',       type=int,  default=N_SAMPLES)
    ap.add_argument('--seed',    type=int,  default=42)
    ap.add_argument('--dry-run', action='store_true')
    args = ap.parse_args()

    rng    = random.Random(args.seed)
    combos = [random_combo(rng) for _ in range(args.n)]
    total  = len(combos)

    ts       = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    out_path = f'data/outputs/param_search_{ts}.csv'
    os.makedirs('data/outputs', exist_ok=True)

    # Estimate time (larger networks are ~2× slower)
    est_min = sum(
        0.5 if c['hidden_dim'] == 32 else (1.2 if c['hidden_dim'] == 128 else 0.75)
        for c in combos
    )

    print(f"\n{'═'*80}")
    print(f"  Random parameter search — mid_clamp_3moment")
    print(f"  Samples      : {total}")
    print(f"  Random seed  : {args.seed}")
    print(f"  Est. time    : {est_min:.0f} min  ({est_min/60:.1f} h)")
    print(f"  Output       : {out_path}")
    print(f"  Axes         : {', '.join(SEARCH.keys())}")
    print(f"{'═'*80}\n")

    if args.dry_run:
        for i, c in enumerate(combos, 1):
            params = ', '.join(f"{k}={v}" for k, v in c.items()
                               if k not in ('void_length', 'void_collinear'))
            print(f"  [{i:3d}] {params}")
        return

    fieldnames = [
        'learning_rate', 'grad_clip', 'chamfer_w', 'hinge_gap_w',
        'coverage_w', 'contact_w', 'anchoring', 'connectivity',
        'hidden_dim', 'num_layers',
        'chamfer', 'loss', 'n_explosions', 'final_grad', 'final_hinge',
        'elapsed_s', 'status',
    ]

    with open(out_path, 'w', newline='') as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()

        for i, combo in enumerate(combos, 1):
            try:
                row = run_combo(combo, i, total)
                writer.writerow(row)
                f.flush()
            except Exception as e:
                print(f"  [{i}/{total}] EXCEPTION: {e}")

    # Clean up
    if os.path.exists(TMP_ARCH):
        os.remove(TMP_ARCH)

    # ── Analysis ──────────────────────────────────────────────────────────────
    rows = []
    with open(out_path) as f:
        rows = [r for r in csv.DictReader(f) if r['status'] == 'ok']

    if not rows:
        print("No successful runs to analyse.")
        return

    rows.sort(key=lambda r: float(r['chamfer']))

    print(f"\n{'═'*80}")
    print(f"  TOP 20 BY CHAMFER   (full results: {out_path})")
    print(f"{'─'*80}")
    hdr = (f"  {'rk':>2}  {'lr':>7}  {'clip':>5}  {'ch_w':>6}  {'hg_w':>6}  "
           f"{'cov':>4}  {'con':>4}  {'anch':>6}  {'conn':>6}  "
           f"{'h':>3}  {'L':>2}  {'chamfer':>10}  {'expl':>4}")
    print(hdr)
    print(f"{'─'*80}")
    for rank, r in enumerate(rows[:20], 1):
        print(
            f"  {rank:2d}  "
            f"{float(r['learning_rate']):>7.4f}  "
            f"{float(r['grad_clip']):>5.1f}  "
            f"{float(r['chamfer_w']):>6.0f}  "
            f"{float(r['hinge_gap_w']):>6.1f}  "
            f"{float(r['coverage_w']):>4.1f}  "
            f"{float(r['contact_w']):>4.1f}  "
            f"{float(r['anchoring']):>6.0f}  "
            f"{float(r['connectivity']):>6.0f}  "
            f"{int(r['hidden_dim']):>3d}  "
            f"{int(r['num_layers']):>2d}  "
            f"{float(r['chamfer']):>10.4e}  "
            f"{r['n_explosions']:>4}"
        )
    print(f"{'─'*80}")

    # Per-axis marginal analysis
    print(f"\n  MARGINAL MEANS (top-30 runs, lower chamfer = better axis value)")
    print(f"{'─'*50}")
    top30 = rows[:min(30, len(rows))]
    for axis, choices in SEARCH.items():
        col = {'chamfer': 'chamfer_w', 'hinge_gap': 'hinge_gap_w',
               'coverage': 'coverage_w', 'contact': 'contact_w'}.get(axis, axis)
        print(f"  {axis:<16}", end='')
        for v in choices:
            subset = [float(r['chamfer']) for r in top30
                      if abs(float(r[col]) - float(v)) < 1e-6]
            mean = sum(subset) / len(subset) if subset else float('nan')
            n    = len(subset)
            print(f"  {v}→{mean:.3e}(n={n})", end='')
        print()
    print(f"{'─'*50}")

    # Recommend best combo
    best = rows[0]
    print(f"\n  RECOMMENDED CONFIG (best chamfer = {float(best['chamfer']):.4e})")
    print(f"{'─'*50}")
    for k in fieldnames[:10]:
        print(f"    {k:<20} {best[k]}")
    print(f"{'─'*50}")
    print(f"\n  Full results: {out_path}")


if __name__ == '__main__':
    main()
